export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const GET_GENRES = 'GET_GENRES';
export const FETCH_FAIL = 'FETCH_FAIL';

export const FETCH_GENRE_REQUEST = 'FETCH_GENRE_REQUEST';
export const FETCH_GENRE_SUCCESS = 'FETCH_GENRE_SUCCESS';
export const FETCH_GENRE_FAILURE = 'FETCH_GENRE_FAILURE';

export const FETCH_TRENDING_REQUEST = 'FETCH_TRENDING_REQUEST';
export const FETCH_TRENDING_SUCCESS = 'FETCH_TRENDING_SUCCESS';
export const FETCH_TRENDING_FAILURE = 'FETCH_TRENDING_FAILURE';

export const GET_LIKED_MOVIES_REQUEST = 'GET_LIKED_MOVIES_REQUEST';
export const GET_LIKED_MOVIES_SUCCESS = 'GET_LIKED_MOVIES_SUCCESS';
export const GET_LIKED_MOVIES_FAILURE = 'GET_LIKED_MOVIES_FAILURE';

export const REMOVE_MOVIE_REQUEST = 'REMOVE_MOVIE_REQUEST';
export const REMOVE_MOVIE_SUCCESS = 'REMOVE_MOVIE_SUCCESS';
export const REMOVE_MOVIE_FAILURE = 'REMOVE_MOVIE_FAILURE';